### ISSUE TITLE
Add a rate limiter

### ISSUE THREAD

**Issue by Codehackerone** [Codehackerone/Medify#5]

**Comment by mohamadaminkarami** [comment]
Hi ,I would like to implement this feature.

**Comment by Codehackerone** [comment]
Hi, whats your status, it has been 2 days

**Comment by Codehackerone** [comment]
> Hi ,I would like to implement this feature.

Whats your update? It has been two days

**Comment by sahilrik** [comment]
i want to work on the issue under jwoc

**Comment by mohamadaminkarami** [comment]
> > Hi ,I would like to implement this feature.
> 
> Whats your update? It has been two days

Hi, please check my pull request. #13
